"""Sync DB with updated code

Revision ID: 26a328ea4062
Revises: f06d7734acfb
Create Date: 2026-05-08 00:37:42.468512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26a328ea4062'
down_revision = 'f06d7734acfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact_messages', sa.Column('reply', sa.Text(), nullable=True))
    op.add_column('contact_messages', sa.Column('replied_at', sa.DateTime(), nullable=True))
    op.alter_column('exam_questions', 'topic',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_questions', 'topic',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('contact_messages', 'replied_at')
    op.drop_column('contact_messages', 'reply')
    # ### end Alembic commands ###
