"""Initial schema and fixes

Revision ID: f06d7734acfb
Revises: 
Create Date: 2026-05-06 00:24:43.898960

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f06d7734acfb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exam_submissions', 'results_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exams', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('exams', 'category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'General'"))
    op.alter_column('exams', 'schedule_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'anytime'"))
    op.alter_column('users', 'failed_login_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_count',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exams', 'schedule_type',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'anytime'"))
    op.alter_column('exams', 'category',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'General'"))
    op.alter_column('exams', 'is_archived',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('exam_submissions', 'results_published',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###
